hdpclient:
  image: local/c7-hdpclient
#  container: hdpclient
  dns:
    - 5.6.7.197
  volumes:
    # sudo docker run d -v /usr/hdp/2.4.0.0-169:/usr/hdp/2.4.0.0-169:rw -v /etc/hadoop:/etc/hadoop:rw -P local/c7-hdpclient:latest
    - /usr/hdp/2.4.0.0-169:/usr/hdp/2.4.0.0-169:ro
    - /usr/hdp/current:/usr/hdp/current:ro
    - /etc/hadoop:/etc/hadoop:ro
#    - /var/log:/var/log


